name: valu_sales
description: "ValU Sales App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: "^3.1.3"
  flutter: "^3.13.6"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.4
  easy_localization: ^3.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  sliver_tools: ^0.2.12
  qr_flutter: ^4.1.0
  dartz: ^0.10.1
  gap: ^3.0.1
  pretty_qr_code: ^3.2.1
  http_parser: ^4.0.2
  injectable: ^2.3.0
  lottie: ^2.6.0
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  json_serializable: ^6.7.1
  loader_overlay: ^2.3.2
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  firebase_core: ^2.17.0
  flutter_countdown_timer: ^4.1.0
  firebase_dynamic_links: ^5.3.7
  firebase_performance: ^0.9.2+7
  firebase_crashlytics: ^3.3.7
  firebase_analytics: ^10.5.1
  valu_ui_kit:
    git:
      url: ../Valu_UI_kit
      ref: main
  valu_network_layer:
    # git:
    #   url: https://gitlab.valu.live/engineering/valu/mobile/valu_network_layer_flutter
    #   ref: master
    path: ../valu_network_layer_flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "resources/icons/app_icon.png"
  adaptive_icon_background: "#FF5100"
  adaptive_icon_foreground: "resources/icons/app_icon.png"
  

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - resources/translation/
    - resources/icons/
    - resources/images/
    - resources/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
